name: 自动打包APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 配置JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: 给gradlew加权限
        run: chmod +x gradlew

      - name: 编译Release APK
        run: ./gradlew clean assembleRelease --stacktrace

      - name: 上传APK文件
        uses: actions/upload-artifact@v4
        with:
          name: 我的APK文件
          # 这里用通配符找APK，不管你的模块叫什么，都能找到！
          path: '**/build/outputs/apk/release/*.apk'
